/*
Generate all subsequence 
------------------------------------------------------------------------------------------------------------------
https://oj.masaischool.com/contest/2464/problem/01
Password : 28891 
------------------------------------------------------------------------------------------------------------------
Description

A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
You are given a string S. You have to generate all the subsequences of the string S using a recursive approach (duplicates allowed)
------------------------------------------------------------------------------------------------------------------
Input Format :

First line of the input contains length of the string S
Second line of the test case contains the string S
------------------------------------------------------------------------------------------------------------------
Constraints :

n <= 18
------------------------------------------------------------------------------------------------------------------
Output

Output all the substring in a particular order. To understand the order of printing, see the sample test case explanation
------------------------------------------------------------------------------------------------------------------
Sample Input 1 

4
abcd
------------------------------------------------------------------------------------------------------------------
Sample Output 1

a
ab
abc
abcd
abd
ac
acd
ad
b
bc
bcd
bd
c
cd
d
------------------------------------------------------------------------------------------------------------------
Hint

Output Explanation :
First output all the subsequences starting with first character.
 When all such subsequences got printed, then move to print all 
 such starting with second chars, and so on.
------------------------------------------------------------------------------------------------------------------*/

const subarrayFromI = (str,ans="",current = 0) =>{
    if( ans.length > 0) console.log(ans);
    if( current == str.length) return;
    
    for( let j = current ; j < str.length ; j++ ){
        ans += str[j];
        subarrayFromI(str,ans,j+1);
        ans = ans.slice(0,-1)
    }
}

function runProgram(input) {
  a = input.split("\n");
  let l = +a[0];
  let str = a[1];
  
  subarrayFromI(str) 
}